fix: remove nonsensitive call from runner_user_data output variable
cattle-ops/terraform-aws-gitlab-runner pull request #1032
Opened 2023-11-08 19:24 UTC by ryancausey

## Description

This removes the nonsensitive call added to the `runner_user_data` output variable in order to fix the issue found in #1031.

Closes #1031.

## Migrations required

NO

## Verification

Running this locally removes the error.

2023-11-08 19:36 UTC, ryancausey commented
I just noticed #1018 and #1019, so I've changed this to always mark this variable as sensitive.

2023-11-10 08:18 UTC, kayman-mk commented
As this variable is already deprecated and used for debugging only, we should simply delete it (like in #1019). Users can set `debug.write_runner_user_data_to_file` to `true` to write the data to the local disk.

2023-11-13 08:13 UTC, kayman-mk requested changes

2023-11-13 08:13 UTC, kayman-mk commented on outputs.tf
>  }
According to #1019 and changing the `nonsensitive` back and forth, I suggest to remove the whole output. It's deprecated and the value is also written to a local file in the `debug/` directory.

2023-11-13 09:46 UTC, kayman-mk approved these changes

2023-11-13 09:47 UTC, merged

2023-11-13 09:47 UTC, kayman-mk commented
Thanks for improving the module, @ryancausey