fix: always add policy to maintain SSM parameters
cattle-ops/terraform-aws-gitlab-runner pull request #510
Opened 2022-06-19 11:15 UTC by kayman-mk

## Description

According to #509 the Runner always maintains a SSM parameter. Thus it needs the policy to be able to to so.

This MR removes the possibility to steer whether or not to add the policy to allow the Runner to `ssm:GetParameter` and `ssm:PutParameter`. The variable `enable_manage_gitlab_token` is marked as deprecated and no longer evaluated.

Fixes #509 

## Migrations required

No

## Verification

None

## Documentation

We use [pre-commit](https://pre-commit.com/) to update the Terraform inputs and outputs in the documentation via [terraform-docs](https://github.com/terraform-docs/terraform-docs). Ensure you have installed those components.

2022-06-19 11:49 UTC, JulianCBC commented
Looks good to me, however we should probably make it explicit that the variable now does nothing, not just "deprecated".

Maybe something like:

```
Ignored and deprecated: This variable used to disable management of the SSM property containing the runner token, meaning that the user-data script still created it, but it wasn't managed by terraform. The runner token is now always stored in a terraform managed SSM property.
```

2022-06-19 14:28 UTC, kayman-mk commented
Good point. Fixed that.

2022-06-20 19:59 UTC, npalm approved these changes
@kayman-mk  looks good! Thx

2022-06-22 21:35 UTC, rewb0rn commented
As discussed in #509 this MR should probably not be merged. Setting `enable_manage_gitlab_token` to false allows to reuse the previous runner registration when `terraform apply` is executed (contrary to registering a new runner in the gitlab server when the value is set to true).

2022-08-06 08:09 UTC, kayman-mk commented
@npalm Can we decide for one way here? Either a) remove the whole functionality as it is not working at the moment and according to your comment in #509 this belongs to an old scenario which is superfluous now or b) fix it.

I propose to remove this function too as the automatic registration process is less error prone.

2022-08-06 10:00 UTC, npalm commented
Not close to a computer this weekend. The automatic registration is the default, right? There where we request gitlab for a token. The other option is legacy for day zero as far I remember. 

So suggest we remove the function. I can have a quick look Monday evening

2022-08-06 17:35 UTC, kayman-mk commented
Automatic registration is the default, true.

2022-08-15 20:36 UTC, npalm commented
So we can close this one, since we will remove automatic registration. OK?

2022-08-16 21:56 UTC, kayman-mk commented
Not 100% sure. This is a quick one solving the problem. The mentioned correct solution could take some time to be completed and could also be a breaking change.

But closing this one would be ok from my side.

2022-12-31 16:35 UTC, npalm commented
@kayman-mk should I test this PR? Can do this next week? Feel free to merge the PR.

2023-01-05 23:27 UTC, npalm requested changes
Testing the PR at the moment, have some troubles. So for that reason mark it as `request for changes`

2023-01-05 23:32 UTC, npalm commented
For some reason the agent is not staring after applying changes. So blocking the merge for the momet. Sorry

2023-01-06 13:54 UTC, kayman-mk commented
Branch updated

2023-01-06 13:55 UTC, kayman-mk commented
Let me test this as well. Should be running as nothing has been removed from the policies.

2023-01-06 14:14 UTC, kayman-mk commented
@npalm This branch is running in my environment. Deployed a runner and executed one job successfully.

2023-01-07 10:07 UTC, npalm commented
> @npalm This branch is running in my environment. Deployed a runner and executed one job successfully.

Will run a test asap. Assume it is now fine. Thanks!

2023-03-02 15:01 UTC, kayman-mk commented
@npalm Seems to be ready now.

2023-03-02 15:36 UTC, npalm commented on main.tf
>    count = var.enable_manage_gitlab_token ? 1 : 0
Here the variable is still used. Evoluation will now cause an error, since the value is always null.

2023-03-02 15:38 UTC, npalm approved these changes

2023-03-02 15:38 UTC, merged